### ISSUE TITLE
Feature Request : mailto links for email. 

### ISSUE THREAD

**Issue by iev6** [akshayrangasai/IITMLatextResume#1]
My first feature request. _Yay_ 
We need to use another package : hyperref, which is generally part of your local package repo, so no extra downloads necessary.

I have written a small macro that does this. Please tell me how to add this.

**Comment by akshayrangasai** [comment]
Good stuff

**Comment by akshayrangasai** [comment]
Please add an underline using \underline{..} and a colour to it as well. Will close issue post those changes.

**Comment by akshayrangasai** [comment]
Closing because this notification keeps paining me
